{
"PulseSensor":
	{
		"LatestVerison":"V1.1",
		"Url":"https://www.demo.com/Demo_v1.1.exe",
		"UpdateTime":"2019-03-31",
      		"ReleaseNote":"\n1.添加检查更新说明，包含版本号，下载链接，更新时间，更新说明.\n2.优化“关于”界面"
	},
"RGBContrl":
	{
		"LatestVerison":"V1.0",
		"Url":"https://www.demo.com/Demo_v1.1.exe",
		"UpdateTime":"2019-03-30",
       		"ReleaseNote":"版本说明"
	}
}
